import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'English';
  late SharedPreferences _prefs;

  final Map<String, Map<String, String>> _translations = {
    'English': {
      // Profile menu
      'edit_profile': 'Edit Profile',
      'saved_addresses': 'Saved Addresses',
      'payment_methods': 'Payment Methods',
      'order_history': 'Order History',
      'favorite_laundries': 'Favorite Laundries',
      'notifications': 'Notifications',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'help_faq': 'Help & FAQ',
      'contact_us': 'Contact Us',
      'about': 'About',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      // Home screen
      'home': 'Home',
      'search': 'Search laundry...',
      'nearby': 'Nearby',
      'bookings': 'Bookings',
      'offers': 'Offers',
      'profile': 'Profile',
      'your_bag': 'Your Bag',
      'popular_laundries': 'Popular Laundries',
      'special_offers': 'Special Offers',
      'top_services': 'Top Services',
      'cart_empty': 'Your cart is empty',
      'add_items': 'Add items to your cart',
      'continue_shopping': 'Continue Shopping',
      'proceed_checkout': 'Proceed to Checkout',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'tax': 'Tax',
      'schedule_pickup': 'Schedule Pickup',
      'schedule_store_visit': 'Schedule Store Visit',
      'delivery_address': 'Delivery Address',
      'pickup_date': 'Pickup Date',
      'pickup_time': 'Pickup Time',
      'delivery_mode': 'Delivery Mode',
      'express': 'Express (2-3 hours)',
      'standard': 'Standard (4-6 hours)',
      'economy': 'Economy (Next day)',
      'continue': 'Continue',
      'back': 'Back',
      'services': 'Services',
      'laundries': 'Laundries',
      'wash': 'Wash',
      'dry_clean': 'Dry Clean',
      'iron': 'Iron',
      'orders': 'Orders',
      'settings': 'Settings',
      'support': 'Support',
      'account': 'Account',
      'logout': 'Logout',
      'confirm_logout': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'save_changes': 'Save Changes',
      'add_card': 'Add Card',
      'add_address': 'Add Address',
      'credit_debit_card': 'Credit/Debit Card',
      'digital_wallet': 'Digital Wallet',
      'set_default': 'Set as default',
      'removed_favorites': 'Removed from favorites',
      'reorder': 'Reorder',
      'close': 'Close',
      'order_confirmed': 'Order Confirmed!',
      'order_id': 'Order ID',
      'track_order': 'Track Order',
      'back_home': 'Back to Home',
    },
    'Indonesia': {
      // Profile menu
      'edit_profile': 'Edit Profil',
      'saved_addresses': 'Alamat Tersimpan',
      'payment_methods': 'Metode Pembayaran',
      'order_history': 'Riwayat Pesanan',
      'favorite_laundries': 'Laundry Favorit',
      'notifications': 'Notifikasi',
      'language': 'Bahasa',
      'dark_mode': 'Mode Gelap',
      'help_faq': 'Bantuan & FAQ',
      'contact_us': 'Hubungi Kami',
      'about': 'Tentang',
      'privacy_policy': 'Kebijakan Privasi',
      'terms_of_service': 'Ketentuan Layanan',
      // Home screen
      'home': 'Beranda',
      'search': 'Cari laundry...',
      'nearby': 'Terdekat',
      'bookings': 'Pesanan',
      'offers': 'Penawaran',
      'profile': 'Profil',
      'your_bag': 'Tas Anda',
      'popular_laundries': 'Laundry Populer',
      'special_offers': 'Penawaran Khusus',
      'top_services': 'Layanan Teratas',
      'cart_empty': 'Keranjang Anda kosong',
      'add_items': 'Tambahkan item ke keranjang Anda',
      'continue_shopping': 'Lanjutkan Belanja',
      'proceed_checkout': 'Lanjutkan ke Checkout',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Biaya Pengiriman',
      'tax': 'Pajak',
      'schedule_pickup': 'Jadwalkan Pengambilan',
      'schedule_store_visit': 'Jadwalkan Kunjungan Toko',
      'delivery_address': 'Alamat Pengiriman',
      'pickup_date': 'Tanggal Pengambilan',
      'pickup_time': 'Waktu Pengambilan',
      'delivery_mode': 'Mode Pengiriman',
      'express': 'Ekspres (2-3 jam)',
      'standard': 'Standar (4-6 jam)',
      'economy': 'Ekonomi (Hari berikutnya)',
      'continue': 'Lanjutkan',
      'back': 'Kembali',
      'services': 'Layanan',
      'laundries': 'Laundry',
      'wash': 'Cuci',
      'dry_clean': 'Dry Clean',
      'iron': 'Setrika',
      'orders': 'Pesanan',
      'settings': 'Pengaturan',
      'support': 'Dukungan',
      'account': 'Akun',
      'logout': 'Keluar',
      'confirm_logout': 'Apakah Anda yakin ingin keluar?',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'edit': 'Edit',
      'save_changes': 'Simpan Perubahan',
      'add_card': 'Tambah Kartu',
      'add_address': 'Tambah Alamat',
      'credit_debit_card': 'Kartu Kredit/Debit',
      'digital_wallet': 'Dompet Digital',
      'set_default': 'Jadikan default',
      'removed_favorites': 'Dihapus dari favorit',
      'reorder': 'Pesan Ulang',
      'close': 'Tutup',
      'order_confirmed': 'Pesanan Dikonfirmasi!',
      'order_id': 'ID Pesanan',
      'track_order': 'Lacak Pesanan',
      'back_home': 'Kembali ke Beranda',
    },
    'Spanish': {
      // Profile menu
      'edit_profile': 'Editar Perfil',
      'saved_addresses': 'Direcciones Guardadas',
      'payment_methods': 'Métodos de Pago',
      'order_history': 'Historial de Pedidos',
      'favorite_laundries': 'Lavanderías Favoritas',
      'notifications': 'Notificaciones',
      'language': 'Idioma',
      'dark_mode': 'Modo Oscuro',
      'help_faq': 'Ayuda y Preguntas Frecuentes',
      'contact_us': 'Contáctanos',
      'about': 'Acerca de',
      'privacy_policy': 'Política de Privacidad',
      'terms_of_service': 'Términos de Servicio',
      // Home screen
      'home': 'Inicio',
      'search': 'Buscar lavandería...',
      'nearby': 'Cerca',
      'bookings': 'Reservas',
      'offers': 'Ofertas',
      'profile': 'Perfil',
      'your_bag': 'Tu Bolsa',
      'popular_laundries': 'Lavanderías Populares',
      'special_offers': 'Ofertas Especiales',
      'top_services': 'Servicios Principales',
      'cart_empty': 'Tu carrito está vacío',
      'add_items': 'Agregar artículos al carrito',
      'continue_shopping': 'Continuar Comprando',
      'proceed_checkout': 'Proceder al Pago',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Tarifa de Entrega',
      'tax': 'Impuesto',
      'schedule_pickup': 'Programar Recogida',
      'schedule_store_visit': 'Programar Visita a la Tienda',
      'delivery_address': 'Dirección de Entrega',
      'pickup_date': 'Fecha de Recogida',
      'pickup_time': 'Hora de Recogida',
      'delivery_mode': 'Modo de Entrega',
      'express': 'Express (2-3 horas)',
      'standard': 'Estándar (4-6 horas)',
      'economy': 'Economía (Día siguiente)',
      'continue': 'Continuar',
      'back': 'Atrás',
      'services': 'Servicios',
      'laundries': 'Lavanderías',
      'wash': 'Lavar',
      'dry_clean': 'Limpieza en Seco',
      'iron': 'Planchar',
      'orders': 'Pedidos',
      'settings': 'Configuración',
      'support': 'Soporte',
      'account': 'Cuenta',
      'logout': 'Cerrar Sesión',
      'confirm_logout': '¿Estás seguro de que quieres cerrar sesión?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'save_changes': 'Guardar Cambios',
      'add_card': 'Agregar Tarjeta',
      'add_address': 'Agregar Dirección',
      'credit_debit_card': 'Tarjeta de Crédito/Débito',
      'digital_wallet': 'Billetera Digital',
      'set_default': 'Establecer como predeterminado',
      'removed_favorites': 'Eliminado de favoritos',
      'reorder': 'Reordenar',
      'close': 'Cerrar',
      'order_confirmed': '¡Pedido Confirmado!',
      'order_id': 'ID de Pedido',
      'track_order': 'Rastrear Pedido',
      'back_home': 'Volver al Inicio',
    },
    'French': {
      // Profile menu
      'edit_profile': 'Modifier le Profil',
      'saved_addresses': 'Adresses Enregistrées',
      'payment_methods': 'Méthodes de Paiement',
      'order_history': 'Historique des Commandes',
      'favorite_laundries': 'Blanchisseries Favorites',
      'notifications': 'Notifications',
      'language': 'Langue',
      'dark_mode': 'Mode Sombre',
      'help_faq': 'Aide et FAQ',
      'contact_us': 'Nous Contacter',
      'about': 'À Propos',
      'privacy_policy': 'Politique de Confidentialité',
      'terms_of_service': 'Conditions d\'Utilisation',
      // Home screen
      'home': 'Accueil',
      'search': 'Chercher une blanchisserie...',
      'nearby': 'À Proximité',
      'bookings': 'Réservations',
      'offers': 'Offres',
      'profile': 'Profil',
      'your_bag': 'Votre Sac',
      'popular_laundries': 'Blanchisseries Populaires',
      'special_offers': 'Offres Spéciales',
      'top_services': 'Services Principaux',
      'cart_empty': 'Votre panier est vide',
      'add_items': 'Ajouter des articles à votre panier',
      'continue_shopping': 'Continuer vos Achats',
      'proceed_checkout': 'Procéder au Paiement',
      'total': 'Total',
      'subtotal': 'Sous-total',
      'delivery_fee': 'Frais de Livraison',
      'tax': 'Taxe',
      'schedule_pickup': 'Programmer un Enlèvement',
      'schedule_store_visit': 'Programmer une Visite au Magasin',
      'delivery_address': 'Adresse de Livraison',
      'pickup_date': 'Date d\'Enlèvement',
      'pickup_time': 'Heure d\'Enlèvement',
      'delivery_mode': 'Mode de Livraison',
      'express': 'Express (2-3 heures)',
      'standard': 'Standard (4-6 heures)',
      'economy': 'Économique (Jour suivant)',
      'continue': 'Continuer',
      'back': 'Retour',
      'services': 'Services',
      'laundries': 'Blanchisseries',
      'wash': 'Laver',
      'dry_clean': 'Nettoyage à Sec',
      'iron': 'Repasser',
      'orders': 'Commandes',
      'settings': 'Paramètres',
      'support': 'Assistance',
      'account': 'Compte',
      'logout': 'Déconnexion',
      'confirm_logout': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'save_changes': 'Enregistrer les Modifications',
      'add_card': 'Ajouter une Carte',
      'add_address': 'Ajouter une Adresse',
      'credit_debit_card': 'Carte de Crédit/Débit',
      'digital_wallet': 'Portefeuille Numérique',
      'set_default': 'Définir par défaut',
      'removed_favorites': 'Supprimé des favoris',
      'reorder': 'Recommander',
      'close': 'Fermer',
      'order_confirmed': 'Commande Confirmée!',
      'order_id': 'Numéro de Commande',
      'track_order': 'Suivre la Commande',
      'back_home': 'Retour à l\'Accueil',
    },
    'German': {
      // Profile menu
      'edit_profile': 'Profil Bearbeiten',
      'saved_addresses': 'Gespeicherte Adressen',
      'payment_methods': 'Zahlungsmethoden',
      'order_history': 'Bestellhistorie',
      'favorite_laundries': 'Lieblingswäschereien',
      'notifications': 'Benachrichtigungen',
      'language': 'Sprache',
      'dark_mode': 'Dunkler Modus',
      'help_faq': 'Hilfe & Häufig Gestellte Fragen',
      'contact_us': 'Kontaktieren Sie uns',
      'about': 'Über uns',
      'privacy_policy': 'Datenschutzrichtlinie',
      'terms_of_service': 'Nutzungsbedingungen',
      // Home screen
      'home': 'Startseite',
      'search': 'Wäscherei suchen...',
      'nearby': 'In der Nähe',
      'bookings': 'Buchungen',
      'offers': 'Angebote',
      'profile': 'Profil',
      'your_bag': 'Ihre Tasche',
      'popular_laundries': 'Beliebte Wäschereien',
      'special_offers': 'Spezialangebote',
      'top_services': 'Top-Dienstleistungen',
      'cart_empty': 'Ihr Wagen ist leer',
      'add_items': 'Artikel in Ihren Wagen legen',
      'continue_shopping': 'Einkaufen fortsetzen',
      'proceed_checkout': 'Zur Kasse',
      'total': 'Gesamt',
      'subtotal': 'Zwischensumme',
      'delivery_fee': 'Liefergebühr',
      'tax': 'Steuer',
      'schedule_pickup': 'Abholfeldler vereinbaren',
      'schedule_store_visit': 'Ladenbesuch vereinbaren',
      'delivery_address': 'Lieferadresse',
      'pickup_date': 'Abholdatum',
      'pickup_time': 'Abholzeit',
      'delivery_mode': 'Lieferart',
      'express': 'Express (2-3 Stunden)',
      'standard': 'Standard (4-6 Stunden)',
      'economy': 'Wirtschaft (Nächster Tag)',
      'continue': 'Fortfahren',
      'back': 'Zurück',
      'services': 'Dienstleistungen',
      'laundries': 'Wäschereien',
      'wash': 'Waschen',
      'dry_clean': 'Trockenreinigung',
      'iron': 'Bügeln',
      'orders': 'Bestellungen',
      'settings': 'Einstellungen',
      'support': 'Unterstützung',
      'account': 'Konto',
      'logout': 'Abmelden',
      'confirm_logout': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'save_changes': 'Änderungen speichern',
      'add_card': 'Karte hinzufügen',
      'add_address': 'Adresse hinzufügen',
      'credit_debit_card': 'Kreditkarte/Debitkarte',
      'digital_wallet': 'Digitale Geldbörse',
      'set_default': 'Als Standard festlegen',
      'removed_favorites': 'Aus Favoriten entfernt',
      'reorder': 'Erneut bestellen',
      'close': 'Schließen',
      'order_confirmed': 'Bestellung Bestätigt!',
      'order_id': 'Bestellnummer',
      'track_order': 'Bestellung verfolgen',
      'back_home': 'Zurück zur Startseite',
    },
    'Chinese': {
      // Profile menu
      'edit_profile': '编辑个人资料',
      'saved_addresses': '保存的地址',
      'payment_methods': '付款方式',
      'order_history': '订单历史',
      'favorite_laundries': '最喜欢的洗衣店',
      'notifications': '通知',
      'language': '语言',
      'dark_mode': '深色模式',
      'help_faq': '帮助和常见问题',
      'contact_us': '联系我们',
      'about': '关于',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      // Home screen
      'home': '主页',
      'search': '搜索洗衣店...',
      'nearby': '附近',
      'bookings': '预订',
      'offers': '优惠',
      'profile': '个人资料',
      'your_bag': '您的购物袋',
      'popular_laundries': '热门洗衣店',
      'special_offers': '特别优惠',
      'top_services': '热门服务',
      'cart_empty': '您的购物车是空的',
      'add_items': '将商品添加到购物车',
      'continue_shopping': '继续购物',
      'proceed_checkout': '继续结账',
      'total': '总计',
      'subtotal': '小计',
      'delivery_fee': '送货费',
      'tax': '税金',
      'schedule_pickup': '安排取货',
      'schedule_store_visit': '安排门店访问',
      'delivery_address': '送货地址',
      'pickup_date': '取货日期',
      'pickup_time': '取货时间',
      'delivery_mode': '送货方式',
      'express': '快速（2-3小时）',
      'standard': '标准（4-6小时）',
      'economy': '经济（次日）',
      'continue': '继续',
      'back': '返回',
      'services': '服务',
      'laundries': '洗衣店',
      'wash': '洗衣',
      'dry_clean': '干洗',
      'iron': '熨烫',
      'orders': '订单',
      'settings': '设置',
      'support': '支持',
      'account': '账户',
      'logout': '登出',
      'confirm_logout': '您确定要登出吗?',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'save_changes': '保存更改',
      'add_card': '添加卡片',
      'add_address': '添加地址',
      'credit_debit_card': '信用卡/借记卡',
      'digital_wallet': '数字钱包',
      'set_default': '设为默认',
      'removed_favorites': '已从收藏夹中移除',
      'reorder': '重新订购',
      'close': '关闭',
      'order_confirmed': '订单已确认!',
      'order_id': '订单号',
      'track_order': '跟踪订单',
      'back_home': '返回主页',
    },
    'Japanese': {
      // Profile menu
      'edit_profile': 'プロフィールを編集',
      'saved_addresses': '保存されたアドレス',
      'payment_methods': '支払い方法',
      'order_history': '注文履歴',
      'favorite_laundries': 'お気に入りのランドリー',
      'notifications': '通知',
      'language': '言語',
      'dark_mode': 'ダークモード',
      'help_faq': 'ヘルプとFAQ',
      'contact_us': 'お問い合わせ',
      'about': 'について',
      'privacy_policy': 'プライバシーポリシー',
      'terms_of_service': '利用規約',
      // Home screen
      'home': 'ホーム',
      'search': 'ランドリーを検索...',
      'nearby': '近く',
      'bookings': '予約',
      'offers': 'オファー',
      'profile': 'プロフィール',
      'your_bag': 'あなたのバッグ',
      'popular_laundries': '人気のランドリー',
      'special_offers': 'スペシャルオファー',
      'top_services': 'トップサービス',
      'cart_empty': 'カートは空です',
      'add_items': 'カートにアイテムを追加',
      'continue_shopping': 'ショッピングを続ける',
      'proceed_checkout': 'チェックアウトに進む',
      'total': '合計',
      'subtotal': '小計',
      'delivery_fee': '配達料金',
      'tax': '税金',
      'schedule_pickup': 'ピックアップをスケジュール',
      'schedule_store_visit': '店舗訪問をスケジュール',
      'delivery_address': '配達先住所',
      'pickup_date': 'ピックアップ日',
      'pickup_time': 'ピックアップ時間',
      'delivery_mode': '配達方法',
      'express': 'エクスプレス（2-3時間）',
      'standard': '標準（4-6時間）',
      'economy': 'エコノミー（翌日）',
      'continue': '続ける',
      'back': '戻る',
      'services': 'サービス',
      'laundries': 'ランドリー',
      'wash': '洗濯',
      'dry_clean': 'ドライクリーニング',
      'iron': 'アイロン',
      'orders': '注文',
      'settings': '設定',
      'support': 'サポート',
      'account': 'アカウント',
      'logout': 'ログアウト',
      'confirm_logout': 'ログアウトしてもよろしいですか?',
      'cancel': 'キャンセル',
      'delete': '削除',
      'edit': '編集',
      'save_changes': '変更を保存',
      'add_card': 'カードを追加',
      'add_address': 'アドレスを追加',
      'credit_debit_card': 'クレジットカード/デビットカード',
      'digital_wallet': 'デジタルウォレット',
      'set_default': 'デフォルトとして設定',
      'removed_favorites': 'お気に入りから削除',
      'reorder': '再注文',
      'close': '閉じる',
      'order_confirmed': '注文が確認されました!',
      'order_id': '注文ID',
      'track_order': '注文を追跡',
      'back_home': 'ホームに戻る',
    },
  };

  String get currentLanguage => _currentLanguage;

  List<String> get availableLanguages => _translations.keys.toList();

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  LanguageProvider() {
    _initLanguage();
  }

  Future<void> _initLanguage() async {
    _prefs = await SharedPreferences.getInstance();
    _currentLanguage = _prefs.getString('language') ?? 'English';
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    if (_translations.containsKey(language)) {
      _currentLanguage = language;
      await _prefs.setString('language', language);
      notifyListeners();
    }
  }
}
